FROM node:16.17.1-alpine3.15 as build

ARG THEME_VERSION=latest
ENV THEME_VERSION=$THEME_VERSION

ARG UPDATE_DETAILS_URL=http://wordpress.przemyslawspaczek.pl/details.json
ENV UPDATE_DETAILS_URL=$UPDATE_DETAILS_URL

COPY . /usr/src/app
WORKDIR /usr/src/app


RUN apk --no-cache add zip
RUN npm update -g npm
RUN npm install --quiet \
    && npm run create-index \
    && npm run nuxt:build

RUN for i in /usr/src/app/packages/theme/blocks/* ; \
    do \
      echo $i; \
      cd $i  \
    && npm install --quiet  \
    && npm run build ; \
    done

RUN cp -r packages/app/dist/wp-content/themes/zhp-pl/_nuxt packages/theme/ \
    && rm packages/theme/index.php \
    && mv packages/app/dist/index.html packages/theme/index.php \
    && sed -i "s/{VERSION}/${THEME_VERSION}/g" packages/theme/style.css \
    && UPDATE_DETAILS_URL=$(echo $UPDATE_DETAILS_URL | sed -e 's/\//\\\//g') \
    && sed -i "s/{UPDATE_DETAILS_URL}/${UPDATE_DETAILS_URL}/g" packages/theme/functions.php

RUN for i in /usr/src/app/packages/theme/blocks/* ; \
    do \
      echo $i; \
      cd $i;  \
      rm -rf node_modules; \
    done

RUN cd packages; \
    mv theme zhp-pl; \
    zip -r ../zhp-pl.zip zhp-pl/*

FROM alpine:3.15

VOLUME /usr/dist
COPY --from=build /usr/src/app/zhp-pl.zip zhp-pl.zip
CMD mv zhp-pl.zip /usr/dist/zhp-pl.zip