FROM node:16.14.2-alpine3.15 as build

ARG THEME_VERSION latest
ENV THEME_VERSION=$THEME_VERSION

ARG UPDATE_DETAILS_URL http://wordpress.przemyslawspaczek.pl/details.json
ENV UPDATE_DETAILS_URL=$UPDATE_DETAILS_URL

COPY . /usr/src/app
WORKDIR /usr/src/app


RUN apk --no-cache add zip
RUN npm install --quiet
RUN npm run create-index
RUN npm run nuxt:build 

# TODO: może da się jakąś pętlę zrobić?
RUN cd /usr/src/app/packages/theme/blocks/accordion \
    && npm install --quiet  \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/accordion-item \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/button \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/card \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/column \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/divider \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/icon \
    && npm install --quiet \
    && npm run build
RUN cd /usr/src/app/packages/theme/blocks/section \
    && npm install --quiet \
    && npm run build


RUN cp -r packages/app/dist/wp-content/themes/zhp-pl/_nuxt packages/theme/ \
    && rm packages/theme/index.php \
    && mv packages/app/dist/index.html packages/theme/index.php \
    && sed -i "s/{VERSION}/${THEME_VERSION}/g" packages/theme/style.css \
    && UPDATE_DETAILS_URL=$(echo $UPDATE_DETAILS_URL | sed -e 's/\//\\\//g') \
    && sed -i "s/{UPDATE_DETAILS_URL}/${UPDATE_DETAILS_URL}/g" packages/theme/functions.php

# TODO: może da się jakąś pętlę zrobić?
RUN cd packages \
    && mv theme zhp-pl \
    && zip -r ../zhp-pl.zip zhp-pl/* \ 
        -x zhp-pl/blocks/accordion/node_modules/**\* \
        -x zhp-pl/blocks/accordion-item/node_modules/**\* \
        -x zhp-pl/blocks/button/node_modules/**\* \
        -x zhp-pl/blocks/card/node_modules/**\* \
        -x zhp-pl/blocks/column/node_modules/**\* \
        -x zhp-pl/blocks/divider/node_modules/**\* \
        -x zhp-pl/blocks/icon/node_modules/**\* \
        -x zhp-pl/blocks/section/node_modules/**\* 

FROM alpine:3.15

VOLUME /usr/dist
COPY --from=build /usr/src/app/zhp-pl.zip zhp-pl.zip
CMD mv zhp-pl.zip /usr/dist/zhp-pl.zip