name: zhp.pl docker image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: zhpadmin
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker (master)
      uses: docker/build-push-action@v3
      if:  ${{ success() && github.ref == 'refs/heads/master' }}
      with:
        push: true
        tags: |
          gkzhp/zhp-pl:latest
          gkzhp/zhp-pl:${{ github.sha	}}

    - name: Build docker (non-master)
      uses: docker/build-push-action@v3
      if:  ${{  success() && github.ref != 'refs/heads/master' }}
      with:
        push: true
        tags: |
          gkzhp/zhp-pl:${{ github.sha	}}

# based on https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    needs: build
    env:
      IMAGE_TAG: gkzhp/zhp-pl:${{ github.sha }}
      CONTAINER_NAME: zhp-pl-dev
    steps:
      - name: Configure SSH
        run: ${{ secrets.ZHP_PL_SSH_CONFIG }}

      - name: Pull the image
        run: ssh zhp-pl "docker pull $IMAGE_TAG"

      - name: Remove existing container
        run: ssh zhp-pl "docker container rm -f $CONTAINER_NAME"

      - name: Start the server
        run: ssh zhp-pl "docker container run -p 4000:3000 -d --name $CONTAINER_NAME $IMAGE_TAG"